config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :entities

  get 'welcome/upload'
  post 'welcome/upload'

  get 'entities/parse'
  post 'entities/parse'
  get 'entities/entry'
  post 'entities/entry'
  get 'welcome/index'
  get 'resumes/parse'
  post 'resumes/parse'
  resources :resumes do
    resources :information
  end

  root 'welcome#index'

end

app/models/entity.rb
class Entity < ActiveRecord::Base
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
	def parse
		@parsethis = params[:answer]
		@parsearray = @parsethis.split("*")
		i =0
		while i< @parsearray.length
			if @parsearray[i] == "RES"
				@resume = Resume.new
				@resume.title = @parsearray[i+1]
				@resume.date = @parsearray[i+2]
				@resume.save
			elsif @parsearray[i] == "INF"
				@information = Information.new
				@information.firstname = @parsearray[i+1]
				@information.middlename = @parsearray[i+2]
				@information.lastname = @parsearray[i+3]
				@information.phone = @parsearray[i+4]
				@information.street = @parsearray[i+5]
				@information.city = @parsearray[i+6]
				@information.state= @parsearray[i+7]
				@information.zipcode = @parsearray[i+8]
				@information.resume_id = @resume.id
				@information.save
			elsif @parsearray[i] == "OBJ"
				@objective = Objective.new
				@objective.position = @parsearray[i+1]
				@objective.date = @parsearray[i+2]
				@objective.fulltime = @parsearray[i+3]
				@objective.resume_id=@resume.id
				@objective.save
			elsif @parsearray[i] == "EDU"
				@education = Education.new
				@education.school = @parsearray[i+1]
				@education.schoolcode = @parsearray[i+2]
				@education.city	= @parsearray[i+3]
				@education.state = @parsearray[i+4]
				@education.degreetype = @parsearray[i+5]
				@education.degree = @parsearray[i+6]
				@education.graddate = @parsearray[i+7]
				@education.mgpa = @parsearray[i+8]
				@education.gpa =@parsearray[i+9]
				@education.resume_id=@resume.id
				@education.save
			elsif @parsearray[i] == "WRK"
				@work = Work.new
				@work.company = @parsearray[i+1]
				@work.position = @parsearray[i+2]
				@work.datestart = @parsearray[i+3]
				@work.dateend = @parsearray[i+4]
				@work.resume_id = @resume.id
				@work.save
			else
			end
					
				
			i+=1
		end

		redirect_to resumes_path
	end
	def entry
		@resumeid = params[:resumeid]
		@resume = Resume.find(@resumeid)
		@entity = Entity.find(params[:entityid])
		@submission = EntityResume.new
		resumeint=params[:resumeid]
		entityint=params[:entityid]
		@submission.resumeid = resumeint
		@submission.entityid = entityint
		@submission.save

		redirect_to entity_path(@entity)

	end
	def index
		@entities = Entity.all
	end
	def new
		@entity = Entity.new
	end
	def create
		@entity = Entity.new(entity_params)
		@entity.save
		redirect_to @entity
	end

	def show
		@resumelist= Array.new
		@entity= Entity.find(params[:id])
		@entries = EntityResume.where(:entityid => params[:id])
		@entries.each do |x|
			@resume = Resume.find(x.resumeid)
			@resumelist.push(@resume)
		end
		@resumeliststring=""
		@resumelist.each do |x|
			@resumestring = ["*RES",x.title,x.date].join("*")
			@information = Information.find_by(resume_id: x.id)
			if(@information!=nil)
				@infostring = ["*INF",@information.firstname,@information.middlename,@information.lastname,@information.phone,@information.street,@information.city, @information.state,@information.zipcode,].join("*")
			else
				@infostring=""
			end
			@objectivestring=""
			x.objective.each do |x|
				@objectivestring+= ["*OBJ",x.position,x.date,x.fulltime].join("*")
			end
			@educationstring=""
			x.education.each do |x|
				@educationstring+= ["*EDU",x.school,x.schoolcode,x.city,x.state,x.degreetype,x.degree,x.graddate,x.mgpa,x.gpa].join("*")
			end
			@workstring=""
			x.work.each do |x|
				@workstring += ["*WRK",x.company,x.position,x.datestart,x.dateend].join("*")
			end
			@resumeliststring+=@resumestring+@infostring+@objectivestring+@educationstring+@workstring
		end



	end

	private
	def entity_params
		params.require(:entity).permit(:name, :description,:degree,:major,:position,:website,:pic,:resumeid,:entityid)
	end
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/views/entities/entry.html.erb
<div class="container">

<h2>The Resume <%= @resume.title %> has been submitted to <%=@entity.name %></h2>

<%= link_to 'Back', entities_path %> |
</div>

app/views/entities/index.html.erb
 <div class="container">
  <h1>Listing Entities</h1><%= link_to 'New Entity', new_entity_path %>


<div class="col-md-12"> 
  <% @entities.each do |entity| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
      <%= image_tag(entity.pic) %>
        <div class="caption">
          <h3><%= entity.name %></h3>
          <p><%= entity.description%></p>
          <%= link_to 'Show', entity_path(entity) %>
          <%= form_tag entities_entry_path, method: :post do %>
            <%= hidden_field_tag :resumeid, current_user.resumeid %>
            <%= hidden_field_tag :entityid, entity.id %>
            <%= submit_tag("Send Resume", :class => "submit") %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<br>
<br>
</div>

app/views/entities/new.html.erb
<h1> New Entity</h1>

<%= form_for :entity, url: entities_path do |f| %>
  <% if @entity.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@entity.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @entity.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>

  <p>
    <%= f.label :degree %><br>
    <%= f.text_field :degree %>
  </p>
  <p>
    <%= f.label :major %><br>
    <%= f.text_field :major %>
  </p>
  <p>
    <%= f.label :position %><br>
    <%= f.text_field :position %>
  </p>
  <p>
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </p>
  <p>
    <%= f.label :pic %><br>
    <%= f.text_field :pic %><br>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/entities/show.html.erb
<div class="container">

<p>
  <strong>Name:</strong>
  <%= @entity.name %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @entity.description %>
</p>

<p>
  <strong>Degree:</strong>
  <%= @entity.degree%>
</p>

<p>
  <strong>Major:</strong>
  <%= @entity.major %>
</p>

<p>
  <strong>Positions:</strong>
  <%= @entity.position %>
</p>

<p>
  <strong>Website:</strong>
  <%= @entity.website %>
</p>

<table class="table table-striped">
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>School </th>
    <th>Degree</th>
    <th>MGPA/GPA</th>
    <th>Objective</th>
    <th>More</th>
  </tr>
  <% @resumelist.each do |resume| %>
    <tr>
      <% resume.information.each do |info| %>
      <td><%=info.firstname%></td>
      <td><%=info.lastname%></td>
      <% end %>
      <% resume.education.each do |info| %>
      <td><%=info.school %></td>
      <td><%=info.degreetype %> <%=info.degree%></td>
      <td><%=info.mgpa %>/<%=info.gpa%></td>
      <% end %>
      <% resume.objective.each do |obj| %>
      	<td><%=obj.position%></td>
      	<%end%>
      <td><%= link_to 'Show', resume_path(resume) %></td>
  <% end %>
</table>

<div class="well">
<%= @resumeliststring %>
<br>
</div>
<%= form_tag resumes_parse_path, method: :get do %>
  <%= text_area_tag :answer,nil,size:"120x20" %>
  <%= hidden_field_tag :entity, @entity.id %><br>
  <%= submit_tag("Generate Resume(s)", :class => "submit") %>
<% end %>


<%= link_to 'Back', entities_path %> |
<%= link_to 'Edit', edit_entity_path(@entity) %>
</div>