config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :entities

  get 'welcome/upload'
  post 'welcome/upload'

  get 'entities/parse'
  post 'entities/parse'
  get 'entities/entry'
  post 'entities/entry'
  get 'welcome/index'
  get 'resumes/parse'
  post 'resumes/parse'
  resources :resumes do
    resources :information
  end

  root 'welcome#index'

end

app/models/resume.rb
class Resume < ActiveRecord::Base
	has_many :information
	has_many :objective
	has_many :work
	has_many :education
	accepts_nested_attributes_for :information
	validates :title, presence: true, length: { maximum:  20}
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
	def parse
		@parsethis = params[:answer]
		@parsearray = @parsethis.split("*")
		i =0
		while i< @parsearray.length
			if @parsearray[i] == "RES"
				@resume = Resume.new
				@resume.title = @parsearray[i+1]
				@resume.date = @parsearray[i+2]
				@resume.save
				if params[:entity]!=nil && @resume !=nil
					@entry = EntityResume.new
					@entry.resumeid=@resume.id
					@entry.entityid=params[:entity]
					@entry.save
				end
			elsif @parsearray[i] == "INF"
				@information = Information.new
				@information.firstname = @parsearray[i+1]
				@information.middlename = @parsearray[i+2]
				@information.lastname = @parsearray[i+3]
				@information.phone = @parsearray[i+4]
				@information.street = @parsearray[i+5]
				@information.city = @parsearray[i+6]
				@information.state= @parsearray[i+7]
				@information.zipcode = @parsearray[i+8]
				@information.resume_id = @resume.id
				@information.save
			elsif @parsearray[i] == "OBJ"
				@objective = Objective.new
				@objective.position = @parsearray[i+1]
				@objective.date = @parsearray[i+2]
				@objective.fulltime = @parsearray[i+3]
				@objective.resume_id=@resume.id
				@objective.save
			elsif @parsearray[i] == "EDU"
				@education = Education.new
				@education.school = @parsearray[i+1]
				@education.schoolcode = @parsearray[i+2]
				@education.city	= @parsearray[i+3]
				@education.state = @parsearray[i+4]
				@education.degreetype = @parsearray[i+5]
				@education.degree = @parsearray[i+6]
				@education.graddate = @parsearray[i+7]
				@education.mgpa = @parsearray[i+8]
				@education.gpa =@parsearray[i+9]
				@education.resume_id=@resume.id
				@education.save
			elsif @parsearray[i] == "WRK"
				@work = Work.new
				@work.company = @parsearray[i+1]
				@work.position = @parsearray[i+2]
				@work.datestart = @parsearray[i+3]
				@work.dateend = @parsearray[i+4]
				@work.resume_id = @resume.id
				@work.save
			else
			end
					
				
			i+=1
		end
		if params[:entity]!=nil
			redirect_to entity_path(params[:entity])
		else
			redirect_to resumes_path
		end
	end
	def index
		if params[:current] != nil
			@user = User.find(current_user.id)
			@user.resumeid= params[:current]
			@user.save
		end
		@resumes = Resume.where(:userid => current_user.id)
		@resumeliststring=""
		@resumes.each do |x|
			@resumestring = ["*RES",x.title,x.date].join("*")
			@information = Information.find_by(resume_id: x.id)
			if(@information!=nil)
				@infostring = ["*INF",@information.firstname,@information.middlename,@information.lastname,@information.phone,@information.street,@information.city, @information.state,@information.zipcode,].join("*")
			else
				@infostring=""
			end
			@objectivestring=""
			x.objective.each do |x|
				@objectivestring+= ["*OBJ",x.position,x.date,x.fulltime].join("*")
			end
			@educationstring=""
			x.education.each do |x|
				@educationstring+= ["*EDU",x.school,x.schoolcode,x.city,x.state,x.degreetype,x.degree,x.graddate,x.mgpa,x.gpa].join("*")
			end
			@workstring=""
			x.work.each do |x|
				@workstring += ["*WRK",x.company,x.position,x.datestart,x.dateend].join("*")
			end
			@resumeliststring+=@resumestring+@infostring+@objectivestring+@educationstring+@workstring
		end
	end
	def show
		@resume = Resume.find(params[:id])
		@education = Education.find_by(resume_id: @resume.id)
		@information = Information.find_by(resume_id: @resume.id)
		@infostring = ["INF",@information.firstname,@information.middlename,@information.lastname,@information.phone,@information.street,@information.city, @information.state,@information.zipcode].join("*")
		@objectivestring=""
		@resume.objective.each do |x|
			@objectivestring+= ["OBJ",x.position,x.date,x.fulltime].join("*")
		end
		@educationstring=""
		@resume.education.each do |x|
			@educationstring+= ["EDU",x.school,x.schoolcode,x.city,x.state,x.degreetype,x.degree,x.graddate,x.mgpa,x.gpa].join("*")
		end
		@workstring=""
		@resume.work.each do |x|
			@workstring += ["WRK",x.company,x.position,x.datestart,x.dateend].join("*")
		end


	end

	def new
		@resume = Resume.new
		@email = ""
		@phone =""
		@gpa =""
		if params[:email] != nil
			@email = params[:email]
		end
		if params[:phone] != nil
			@phone = params[:phone]
		end
		if params[:gpa] != nil
			@gpa = params[:gpa]
		end
		if params[:firstname] != nil
			@firstname = params[:firstname]
		end
		if params[:lastname] != nil
			@lastname = params[:lastname]
		end
		if params[:degreetype] != nil
			@degreetype = params[:degreetype]
		end
		if params[:city] != nil
			@city = params[:city]
		end
		if params[:degree] != nil
			@degree= params[:degree]
		end
		if params[:state] != nil
			@state = params[:state]
		end
		if params[:zip] != nil
			@zip = params[:zip]
		end

	end

	def edit
		@resume = Resume.find(params[:id])
		@resume.objective.each do |x|
			@objective=x
		end
		@resume.information.each do|x|
			@information =x
		end
		@resume.work.each do |x|
			@work=x
		end
		@resume.education.each do |x|
			@education=x
		end
	end

	def create
		@resume = Resume.new(resume_params)
		@resume.userid = current_user.id
		@resume.save
		@information = Information.new
		@information.resume_id= @resume.id
		@information.firstname = params[:informationfname]
		@information.middlename = params[:INFmiddle]
		@information.lastname = params[:INFlastname]
		@information.phone = params[:INFphone]
		@information.street = params[:INFstreet]
		@information.city = params[:INFcity]
		@information.state = params[:INFstate]
		@information.zipcode = params[:INFzip]
		@information.email = params[:INFemail]
		@information.save

		@objective = Objective.new
		@objective.resume_id = @resume.id
		@objective.position = params[:OBJposition]
		@objective.date = params[:OBJdate]
		@objective.fulltime = params[:OBJfull]
		@objective.save

		@education = Education.new
		@education.resume_id = @resume.id
		@education.school = params[:EDUschool]
		@education.schoolcode = params[:EDUcode]
		@education.city = params[:EDUcity]
		@education.state = params[:EDUstate]
		@education.degree = params[:EDUdegree]
		@education.degreetype = params[:EDUtype]
		@education.graddate = params[:EDUdate]
		@education.mgpa = params[:EDUmgpa]
		@education.gpa = params[:EDUgpa]
		@education.save

		@work = Work.new
		@work.resume_id = @resume.id
		@work.company = params[:WRKcompany]
		@work.position = params[:WRKposition]
		@work.datestart = params[:WRKdatestart]
		@work.dateend = params[:WRKdatend]
		@work.save


			redirect_to @resume

	end


	def destroy
		@resume = Resume.find(params[:id])
		@resume.destroy

		redirect_to resumes_path
	end

	def update
		@resume = Resume.find(params[:id])

		if @resume.update(resume_params)
			redirect_to @resume
		else
			render 'edit'
		end
	end

	private 
		def resume_params
			params.require(:resume).permit(:title,:date, :informationfname, :INFmiddle, :INFlastname, :INFphone, :INFstreet, :INFcity, :INFstate, :INFzip)
			
		end
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/resumes/edit.html.erb
<div class="container">
  <h1> Edit Resume </h1>

<div class="row">
<%= form_for :resume, url: resumes_path do |f| %>
<div class="col-md-6">
  <div class="panel panel-default">
  <div class="panel-heading">New Resume</div>
  <div class="panel-body">
  <% if @resume.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@resume.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @resume.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 </div>
</div>
</div>
<div class="col-md-6">
  <div class="panel panel-default">
  <div class="panel-heading">Contact Information</div>
  <div class="panel-body">
  <p> First Name
  <%= text_field_tag(:informationfname, @information.firstname) %>
  <br> Middle Name
    <%= text_field_tag(:INFmiddle, @information.middlename) %>
  <br>Last Name
    <%= text_field_tag(:INFlastname, @information.lastname) %>
  <br> Phone
    <%= text_field_tag(:INFphone,@information.phone) %>
  <br> Email
    <%= text_field_tag(:INFemail,@information.email) %>
  <br> Street
    <%= text_field_tag(:INFstreet,@information.street) %>
  <br> City
    <%= text_field_tag(:INFcity,@information.city) %>
  <br> State
    <%= text_field_tag(:INFstate,@information.state) %>
  <br> Zip Code
    <%= text_field_tag(:INFzip,@information.zipcode) %>
  </p>
</div>
</div>
</div>
</div>
<div class="row">
<div class="col-md-6">
  <div class="panel panel-default">
  <div class="panel-heading">Objective</div>
  <div class="panel-body">
  <p>Position
    <%= text_field_tag(:OBJposition,@objective.position)  %>
  <br>Time Period of Desired Position
    <%= text_field_tag(:OBJdate,@objective.date) %>
<br> Full Time(Y)/Parttime or Internship(N)
    <%= check_box_tag(:OBJfull,@objective.fulltime) %>
  </p>
</div>
  <div class="panel-heading">Work Experience</div>
  <div class="panel-body">
    <p> Company
      <%= text_field_tag(:WRKcompany,@work.company) %>
      <br> Position 
      <%= text_field_tag(:WRKposition,@work.position) %>
      <br> Start Date
      <%= text_field_tag(:WRKdatestart,@work.datestart) %>
      <br> End Date
      <%= text_field_tag(:WRKdateend,@work.dateend) %>
    </p>
    </div>
</div>
</div>

<div class="col-md-6">
  <div class="panel panel-default">
  <div class="panel-heading">Education</div>
  <div class="panel-body">
    <p>School
      <%= text_field_tag(:EDUschool,@education.school) %>
      <br>School Code
      <%= text_field_tag(:EDUcode, @education.schoolcode) %>
      <br> City
      <%= text_field_tag(:EDUcity,@education.city) %>
      <br>State
      <%= text_field_tag(:EDUstate,@education.state) %>
      <br>Degree Type
      <%= text_field_tag(:EDUtype,@education.degreetype) %>
      <br>Degree
      <%= text_field_tag(:EDUdegree,@education.degree) %>
      <br>Grad Date
      <%= text_field_tag(:EDUdate, @education.graddate) %>
      <br>Major GPA
      <%= text_field_tag(:EDUmgpa,@education.gpa) %>
      <br>GPA
      <%= text_field_tag(:EDUgpa,@education.gpa) %>
    </p>
  </div>
</div>
</div>
</div>

  <p>
    <%= f.submit %>
  </p>
</div>
<% end %>

app/views/resumes/index.html.erb
 <div class="container">
  <h1>Listing Resumes</h1><%= link_to 'New resume', new_resume_path %>

<table class="table table-striped">
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>School </th>
    <th>Degree</th>
    <th>MGPA/GPA</th>
    <th colspan=4>Options</th>
  </tr>
 
  <% @resumes.each do |resume| %>
    <% if resume.id == current_user.resumeid %>
      <tr class="success">
    <% else %>
      <tr>
    <% end %>
      <% resume.information.each do |info| %>
      <td><%=info.firstname%></td>
      <td><%=info.lastname%></td>
      <% end %>
      <% resume.education.each do |info| %>
      <td><%=info.school %></td>
      <td><%=info.degreetype %> <%=info.degree%></td>
      <td><%=info.mgpa %>/<%=info.gpa%></td>
      <% end %>
      <td><%= link_to 'Show', resume_path(resume) %></td>
      <td><%= link_to 'Edit', edit_resume_path(resume) %></td>
      <td><%= link_to 'Destroy', resume_path(resume),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
                  <td><%= link_to 'Make Current', resumes_path(current: resume.id) %></td>

                  </tr>
  <% end %>
</table>
<br>
<div class="well">
<%= @resumeliststring %>
<br>
</div>
<%= form_tag resumes_parse_path, method: :get do %>
  <%= text_area_tag :answer, nil, size: "120x20"%><br>
  <%= submit_tag("Generate Resume(s)", :class => "submit") %>
<% end %>
</div>

app/views/resumes/new.html.erb
<div class="container">
  <h1> New Resume </h1>

<div class="row">
<%= form_for :resume, url: resumes_path do |f| %>
<div class="col-md-6">
  <div class="panel panel-default">
  <div class="panel-heading">New Resume</div>
  <div class="panel-body">
  <% if @resume.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@resume.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @resume.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 </div>
</div>
</div>
<div class="col-md-6">
  <div class="panel panel-default">
  <div class="panel-heading">Contact Information</div>
  <div class="panel-body">
  <p> First Name
  <%= text_field_tag(:informationfname, @firstname) %>
  <br> Middle Name
    <%= text_field_tag(:INFmiddle) %>
  <br>Last Name
    <%= text_field_tag(:INFlastname, @lastname) %>
  <br> Phone
    <%= text_field_tag(:INFphone,@phone) %>
  <br> Email
    <%= text_field_tag(:INFemail,@email) %>
  <br> Street
    <%= text_field_tag(:INFstreet) %>
  <br> City
    <%= text_field_tag(:INFcity,@city) %>
  <br> State
    <%= text_field_tag(:INFstate,@state) %>
  <br> Zip Code
    <%= text_field_tag(:INFzip,@zip) %>
  </p>
</div>
</div>
</div>
</div>
<div class="row">
<div class="col-md-6">
  <div class="panel panel-default">
  <div class="panel-heading">Objective</div>
  <div class="panel-body">
  <p>Position
    <%= text_field_tag(:OBJposition) %>
  <br>Time Period of Desired Position
    <%= text_field_tag(:OBJdate) %>
<br> Full Time(Y)/Parttime or Internship(N)
    <%= check_box_tag(:OBJfull) %>
  </p>
</div>
  <div class="panel-heading">Work Experience</div>
  <div class="panel-body">
    <p> Company
      <%= text_field_tag(:WRKcompany) %>
      <br> Position 
      <%= text_field_tag(:WRKposition) %>
      <br> Start Date
      <%= text_field_tag(:WRKdatestart) %>
      <br> End Date
      <%= text_field_tag(:WRKdateend) %>
    </p>
    </div>
</div>
</div>

<div class="col-md-6">
  <div class="panel panel-default">
  <div class="panel-heading">Education</div>
  <div class="panel-body">
    <p>School
      <%= text_field_tag(:EDUschool) %>
      <br>School Code
      <%= text_field_tag(:EDUcode) %>
      <br> City
      <%= text_field_tag(:EDUcity,@city) %>
      <br>State
      <%= text_field_tag(:EDUstate,@state) %>
      <br>Degree Type
      <%= text_field_tag(:EDUtype,@degreetype) %>
      <br>Degree
      <%= text_field_tag(:EDUdegree,@degree) %>
      <br>Grad Date
      <%= text_field_tag(:EDUdate) %>
      <br>Major GPA
      <%= text_field_tag(:EDUmgpa,@gpa) %>
      <br>GPA
      <%= text_field_tag(:EDUgpa,@gpa) %>
    </p>
  </div>
</div>
</div>
</div>

  <p>
    <%= f.submit %>
  </p>
</div>
<% end %>

app/views/resumes/parse.html.erb
<h1>Listing Resumes</h1>

app/views/resumes/show.html.erb
<div class="container">
<p>
  <strong>Title:</strong>
  <%= @resume.title %>
</p>
 
<p>
  <strong>Date:</strong>
  <%= @resume.created_at %>
</p>
<br>
<div class="row">
<% @resume.information.each do |information| %>
<div class="col-md-6">
	<div class="panel panel-default">
	<div class="panel-heading">Contact Information</div>
	<div class="panel-body">
	<%= information.firstname %> <%=information.middlename%> <%=information.lastname%> 
	<br>Contact Information
	<br>Email: <%= information.email%> Phone: <%= information.phone %> 
	<br><%= information.street %> 
	<br><%= information.city %> <%=information.state%> <%=information.zipcode%>
</div>
</div>
</div>
<% end %>

<% @resume.objective.each do |objective| %>
<div class="col-md-6">
	<div class="panel panel-default">
		<div class="panel-heading">Objective</div>
		<div class="panel-body">
		<%= objective.position %> Date: <%=objective.date %> Fulltime:
		<% if objective.fulltime == true %>
			Yes
		<% else %>
			No
		<%end%>
	</div>
	</div>
</div>
<%end%>
</div>
<div class="row">
<% @resume.education.each do |education| %>
<div class="col-md-6">
	<div class="panel panel-default">
		<div class="panel-heading">Education</div>
		<div class="panel-body">
		School: <%= education.school + " "+ education.schoolcode+" "+education.city + " " + education.state  %> 
		<br>Degree: <%= education.degreetype + " " + education.degree + " " + education.graddate %>
		<br>Major GPA: <%= education.mgpa %> GPA: <%=education.gpa%>
	</div>
</div>
</div>
<% end %>

<% @resume.work.each do |work| %>
<div class="col-md-6">
	<div class="panel panel-default">
		<div class="panel-heading">Work Experience</div>
		<div class="panel-body">
		Company: <%= work.company %> Position: <%= work.position %> Start Date: <%= work.datestart %> End Date <%=work.dateend%>
	</div>
</div>
<% end %>
</div>
</div>
<div class="row">
<h3>Standard Resume Format</h3>
<div class="well">
	RES*<%=@resume.title%>*<%=@resume.created_at%>~<br>
	<%= @infostring %><br>
	<%= @objectivestring %><br>
	<%= @educationstring %><br>
	<%= @workstring %>
</div>

<%= link_to 'Back', resumes_path %> |
<%= link_to 'Edit', edit_resume_path(@resume) %>
</div>